# Working directory is now /workspace
steps:
# Deploy to GKE kluster
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', '/workspace/deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=central-cluster'

logsBucket: 'fulfilment_platform_logs'
tags:
  - "java-web"
  - "production-release"
  - "central-cluster"
