# Working directory is now /workspace
steps:
# Pull and decrypt secrets
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=id_fulfilment-platform.enc
  - --plaintext-file=id_fulfilment-platform
  - --location=global
  - --keyring=fulfilment-platform
  - --key=scripts-deploy-key

# Build Dockerfile
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--build-arg', 'PROJECT_ID=$PROJECT_ID', '--cache-from', 'gcr.io/$PROJECT_ID/java-web:latest', '-t', 'gcr.io/$PROJECT_ID/java-web:$BRANCH_NAME-$REVISION_ID', '-t', 'gcr.io/$PROJECT_ID/java-web:latest', '.' ]

# Push image to gcr
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/java-web:$BRANCH_NAME-$REVISION_ID"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/java-web:latest"]

# Deploy to cluster TBD
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', '/workspace/deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=central-cluster'


logsBucket: 'fulfilment_platform_logs'
tags:
  - "java"

# Save image in Container Registry
images: 
  - 'gcr.io/$PROJECT_ID/java-web:$BRANCH_NAME-$REVISION_ID'
  - 'gcr.io/$PROJECT_ID/java-web:latest'
