# Working directory is now /workspace
steps:
# Pull and decrypt secrets
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=id_fulfilment-platform.enc
  - --plaintext-file=id_fulfilment-platform
  - --location=global
  - --keyring=ssh-keys
  - --key=fulfilment-platform

# Build Dockerfile
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/java-web:$BRANCH_NAME-$REVISION_ID', '.' ]

# Push image Container Registry
  images: 'gcr.io/$PROJECT_ID/java-web:$BRANCH_NAME-$REVISION_ID'
# Working directory is now /workspace

# Deploy to cluster TBD
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/fulfilment-platform-deployment'
  - 'my-container=gcr.io/#PROJECT_ID/java-web:$BRANCH_NAME-$REVISION_ID'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

  tags:
    - "java"
    - "web-frontend"
    - "logic-backend"
