apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: prod-cluser
  labels:
      app: java-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-web
  template:
    metadata:
      labels:
        app: java-web
        role: master
        tier: frontend
    spec:
      containers:
      - name: java-web
        image: gcr.io/fulfillment-platform/java-web
        ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https