apiVersion: v1
kind: Service
metadata:
  name: fulfillment-platform
  labels:
    app: java-web
spec:
  type: NodePort
  ports:
  - port: 8089
    nodePort: 30045
  selector:
    app: java-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fulfillment-platform
  labels:
      app: java-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-web
  template:
    metadata:
      labels:
        app: java-web
        tier: prod
        repo: fulfillment-platform
        branch: master
    spec:
      containers:

        # Java applicaiton
        - name: java-web
          image: gcr.io/zip-zap-gateway/java-web:master
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
          readinessProbe:
            httpGet:
                path: /health
                port: 8089
            initialDelaySeconds: 45
            periodSeconds: 5
            timeoutSeconds: 5
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password 
            - name: OKTA_ISSUER
              valueFrom:
                secretKeyRef:
                  name: okta-oauth
                  key: issuer
            - name: OKTA_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: okta-oauth
                  key: clientId
            - name: OKTA_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: okta-oauth
                  key: clientSecret

        # Sidecar cloud mysql proxy
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=zip-zap-gateway:us-central1:supplier-master=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true

      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:
