apiVersion: v1
kind: Service
metadata:
  name: fulfillment-platform
  labels:
    app: java-web
spec:
  type: NodePort
  ports:
  - port: 8089
    nodePort: 30060
  selector:
    app: java-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fulfillment-platform
  labels:
      app: java-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-web
  template:
    metadata:
      labels:
        app: java-web
        tier: prod
        repo: fulfillment-platform
        branch: master
    spec:
      containers:
      - name: java-web
        image: gcr.io/fulfillment-platform/java-web
        ports:
          - containerPort: 8089