version: 2
jobs:
  build:
    working_directory: /build
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install CI enviorment dependencies
          command: |
            apk add --no-cache openssl py-pip=9.0.0-r1
            openssl aes-256-cbc -d -in id_fulfilment-platform-circle.enc -out id_fulfilment-platform -k $SCRIPTS_SSH; exit 0
            pip install docker-compose==1.19.0
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker-compose build
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar java-web
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
